// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package entities

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson89020eaDecodeGolangTestTaskInternalEntities(in *jlexer.Lexer, out *GetAdAnswer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "status":
			out.Status = ResultStatus(in.String())
		case "result":
			if in.IsNull() {
				in.Skip()
				out.Result = nil
			} else {
				if out.Result == nil {
					out.Result = new(APIAdItem)
				}
				(*out.Result).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson89020eaEncodeGolangTestTaskInternalEntities(out *jwriter.Writer, in GetAdAnswer) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"result\":"
		out.RawString(prefix)
		if in.Result == nil {
			out.RawString("null")
		} else {
			(*in.Result).MarshalEasyJSON(out)
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetAdAnswer) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson89020eaEncodeGolangTestTaskInternalEntities(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetAdAnswer) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson89020eaEncodeGolangTestTaskInternalEntities(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetAdAnswer) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson89020eaDecodeGolangTestTaskInternalEntities(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetAdAnswer) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson89020eaDecodeGolangTestTaskInternalEntities(l, v)
}
func easyjson89020eaDecodeGolangTestTaskInternalEntities1(in *jlexer.Lexer, out *APIAdItem) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "title":
			out.Title = string(in.String())
		case "price":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Price).UnmarshalJSON(data))
			}
		case "main_image_url":
			if in.IsNull() {
				in.Skip()
				out.MainImageURL = nil
			} else {
				if out.MainImageURL == nil {
					out.MainImageURL = new(string)
				}
				*out.MainImageURL = string(in.String())
			}
		case "description":
			out.Description = string(in.String())
		case "image_urls":
			if in.IsNull() {
				in.Skip()
				out.ImageURLs = nil
			} else {
				in.Delim('[')
				if out.ImageURLs == nil {
					if !in.IsDelim(']') {
						out.ImageURLs = make([]string, 0, 4)
					} else {
						out.ImageURLs = []string{}
					}
				} else {
					out.ImageURLs = (out.ImageURLs)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.ImageURLs = append(out.ImageURLs, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson89020eaEncodeGolangTestTaskInternalEntities1(out *jwriter.Writer, in APIAdItem) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Raw((in.Price).MarshalJSON())
	}
	{
		const prefix string = ",\"main_image_url\":"
		out.RawString(prefix)
		if in.MainImageURL == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.MainImageURL))
		}
	}
	if in.Description != "" {
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	if len(in.ImageURLs) != 0 {
		const prefix string = ",\"image_urls\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v2, v3 := range in.ImageURLs {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v APIAdItem) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson89020eaEncodeGolangTestTaskInternalEntities1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v APIAdItem) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson89020eaEncodeGolangTestTaskInternalEntities1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *APIAdItem) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson89020eaDecodeGolangTestTaskInternalEntities1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *APIAdItem) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson89020eaDecodeGolangTestTaskInternalEntities1(l, v)
}
